name: Build and publish v1 API docs

on:
  push:
    branches: [v1_release]
    paths: 
      - docfx/**

permissions:
  id-token: write 
  pages: write

jobs:
  deploy:
    name: Build and Deploy API docs to github-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: DocFX Build
      working-directory: docfx
      run: |
        dotnet tool install -g docfx
        $env:DOCFX_SOURCE_BRANCH_NAME="${{ github.ref_name }}"
        docfx metadata
        docfx build
      continue-on-error: false

    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docfx/_site
       
    - name: v1_release Repository Dispatch ${{ github.ref_name }}
      if: github.ref_name == 'v1_release'
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.V2DOCS_TOKEN }}
        repository: gui-cs/Terminal.GuiV1Docs
        event-type: v1_release_push
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'